version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - HOST=${HOST}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
