name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.13.0"

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build project
        run: npm run build --prod

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 194.113.35.10 >> ~/.ssh/known_hosts

      - name: Change permissions on the remote server
        run: |
          ssh zeto@194.113.35.10 "sudo chown -R zeto:zeto /home/zeto/frontend && sudo chmod -R 755 /home/zeto/frontend"

      - name: Deploy
        run: |
          scp -r dist/ zeto@194.113.35.10:/home/zeto/frontend
